export const data = [
    { name: "التكوين", chapters: 50, value: 1 },
    { name: "الخروج", chapters: 40, value: 2 },
    { name: "اللاويين", chapters: 27, value: 3 },
    { name: "العدد", chapters: 36, value: 4 },
    { name: "التثنية", chapters: 34, value: 5 },
    { name: "يشوع", chapters: 24, value: 6 },
    { name: "القضاة", chapters: 21, value: 7 },
    { name: "راعوث", chapters: 4, value: 8 },
    { name: "صموئيل الأول", chapters: 31, value: 9 },
    { name: "صموئيل الثاني", chapters: 24, value: 10 },
    { name: "الملوك الأول", chapters: 22, value: 11 },
    { name: "الملوك الثاني", chapters: 25, value: 12 },
    { name: "أخبار الأيام الأول", chapters: 29, value: 13 },
    { name: "أخبار الأيام الثاني", chapters: 36, value: 14 },
    { name: "عزرا", chapters: 10, value: 15 },
    { name: "نحميا", chapters: 13, value: 16 },
    { name: "أستير", chapters: 10, value: 17 },
    { name: "أيوب", chapters: 42, value: 18 },
    { name: "المزامير", chapters: 150, value: 19 },
    { name: "الأمثال", chapters: 31, value: 20 },
    { name: "الجامعة", chapters: 12, value: 21 },
    { name: "نشيد الأنشاد", chapters: 8, value: 22 },
    { name: "إشعياء", chapters: 66, value: 23 },
    { name: "إرميا", chapters: 52, value: 24 },
    { name: "مراثي إرميا", chapters: 5, value: 25 },
    { name: "حزقيال", chapters: 48, value: 26 },
    { name: "دانيال", chapters: 12, value: 27 },
    { name: "هوشع", chapters: 14, value: 28 },
    { name: "يوئيل", chapters: 3, value: 29 },
    { name: "عاموس", chapters: 9, value: 30 },
    { name: "عوبديا", chapters: 1, value: 31 },
    { name: "يونان", chapters: 4, value: 32 },
    { name: "ميخا", chapters: 7, value: 33 },
    { name: "ناحوم", chapters: 3, value: 34 },
    { name: "حبقوق", chapters: 3, value: 35 },
    { name: "صفنيا", chapters: 3, value: 36 },
    { name: "حجى", chapters: 2, value: 37 },
    { name: "زكريا", chapters: 14, value: 38 },
    { name: "ملاخي", chapters: 4, value: 39 },
    { name: "متى", chapters: 28, value: 40 },
    { name: "مرقس", chapters: 16, value: 41 },
    { name: "لوقا", chapters: 24, value: 42 },
    { name: "يوحنا", chapters: 21, value: 43 },
    { name: "أعمال الرسل", chapters: 28, value: 44 },
    { name: "رومية", chapters: 16, value: 45 },
    { name: "كورنثوس الأولى", chapters: 16, value: 46 },
    { name: "كورنثوس الثانية", chapters: 13, value: 47 },
    { name: "غلاطية", chapters: 6, value: 48 },
    { name: "أفسس", chapters: 6, value: 49 },
    { name: "فيلبي", chapters: 4, value: 50 },
    { name: "كولوسي", chapters: 4, value: 51 },
    { name: "تسالونيكي الأولى", chapters: 5, value: 52 },
    { name: "تسالونيكي الثانية", chapters: 3, value: 53 },
    { name: "تيموثاوس الأولى", chapters: 6, value: 54 },
    { name: "تيموثاوس الثانية", chapters: 4, value: 55 },
    { name: "تيطس", chapters: 3, value: 56 },
    { name: "فليمون", chapters: 1, value: 57 },
    { name: "العبرانيين", chapters: 13, value: 58 },
    { name: "يعقوب", chapters: 5, value: 59 },
    { name: "بطرس الأولى", chapters: 5, value: 60 },
    { name: "بطرس الثانية", chapters: 3, value: 61 },
    { name: "يوحنا الأولى", chapters: 5, value: 62 },
    { name: "يوحنا الثانية", chapters: 1, value: 63 },
    { name: "يوحنا الثالثة", chapters: 1, value: 64 },
    { name: "يهوذا", chapters: 1, value: 65 },
    { name: "الرؤيا", chapters: 22, value: 66 },
  ];